"use strict";const e=require("electron"),n=require("node:path"),h=require("./executor-CmfbmGNi.cjs"),o=require("node:fs/promises");var d=typeof document<"u"?document.currentScript:null;const p=n.dirname(new URL(typeof document>"u"?require("url").pathToFileURL(__filename).href:d&&d.tagName.toUpperCase()==="SCRIPT"&&d.src||new URL("main.cjs",document.baseURI).href).pathname);process.env.DIST=n.join(p,"../dist");process.env.VITE_PUBLIC=e.app.isPackaged?process.env.DIST:n.join(process.env.DIST,"../public");const m=process.env.DIST||"",v=process.env.VITE_PUBLIC||"";let l;const w=process.env.VITE_DEV_SERVER_URL,c=process.env.SKILLS_DIR||(e.app.isPackaged?n.join(e.app.getPath("userData"),"skills"):n.resolve(p,"../../../skills"));function f(){l=new e.BrowserWindow({width:1200,height:800,icon:n.join(v,"vite.svg"),webPreferences:{preload:n.join(p,"preload.js")}}),l.webContents.on("did-finish-load",()=>{l?.webContents.send("main-process-message",new Date().toLocaleString())}),w?l.loadURL(w):l.loadFile(n.join(m,"index.html"))}e.app.on("window-all-closed",()=>{process.platform!=="darwin"&&(e.app.quit(),l=null)});e.app.on("activate",()=>{e.app.isReady()&&e.BrowserWindow.getAllWindows().length===0&&f()});e.app.whenReady().then(async()=>{try{await o.access(c)}catch{console.log(`Creating skills directory at ${c}`),await o.mkdir(c,{recursive:!0})}f()});e.ipcMain.handle("get-skills",async()=>{console.log(`Scanning skills in: ${c}`);const s=await new h.SkillScanner(c).scan(),t=new h.SkillParser,r=[];for(const a of s)try{const i=await t.parse(a.skillMdPath),g=await o.readFile(a.skillMdPath,"utf-8");r.push({...a,metadata:i,content:g})}catch(i){console.error(i),r.push({...a,error:String(i)})}return r});e.ipcMain.handle("save-skill",async(u,s,t)=>{try{return await o.writeFile(s,t,"utf-8"),{success:!0}}catch(r){return{success:!1,error:r.message}}});e.ipcMain.handle("run-skill",async(u,s,t,r)=>{const a=new h.SkillExecutor;try{return console.log(`Running skill at ${s} with script ${t} and args`,r),{success:!0,output:await a.execute(s,t,r)}}catch(i){return{success:!1,error:i.message}}});e.ipcMain.handle("create-skill",async(u,s)=>{if(!s||!/^[a-zA-Z0-9-_]+$/.test(s))return{success:!1,error:"Invalid skill name"};const t=n.join(c,s),r=n.join(t,"SKILL.md");try{await o.mkdir(t,{recursive:!0});const a=`---
name: ${s}
description: A new skill
parameters:
  input:
    type: string
    description: Input parameter
---
# ${s}
Enter your skill logic here.
`;return await o.writeFile(r,a,"utf-8"),{success:!0}}catch(a){return{success:!1,error:a.message}}});e.ipcMain.handle("delete-skill",async(u,s)=>{try{return s.startsWith(c)?(await o.rm(s,{recursive:!0,force:!0}),{success:!0}):{success:!1,error:"Access denied"}}catch(t){return{success:!1,error:t.message}}});e.ipcMain.handle("get-app-info",()=>({skillsDir:c,serverPath:n.join(p,"mcp-server.cjs"),appPath:e.app.getAppPath(),exePath:process.execPath}));
